name: MustafaGuvenc
favicon: null
layout_spectrum: 0.9214669626671821
typography_spectrum: 0.9834374352358282
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.47756767831742764
  lightness: 0.5749775229487568
  saturation: 0.7761365571059287
  rhythmicContrast: 0.6567078055813909
purpose: []
